# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{remember-the-ruby}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2009-10-21}
  s.default_executable = %q{rtr}
  s.description = %q{http://peervoice.com/software/remember-the-ruby}
  s.email = %q{<ddollar@gmail.com>}
  s.executables = ["rtr"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION",
     "bin/.placeholder",
     "bin/rtr",
     "doc/.placeholder",
     "lib/core_ext/datetime.rb",
     "lib/core_ext/enumerable.rb",
     "lib/core_ext/fixnum.rb",
     "lib/core_ext/nil.rb",
     "lib/core_ext/string.rb",
     "lib/remember-the-ruby.rb",
     "lib/remember-the-ruby/api.rb",
     "lib/remember-the-ruby/contact.rb",
     "lib/remember-the-ruby/entity.rb",
     "lib/remember-the-ruby/entity_list.rb",
     "lib/remember-the-ruby/group.rb",
     "lib/remember-the-ruby/list.rb",
     "lib/remember-the-ruby/location.rb",
     "lib/remember-the-ruby/note.rb",
     "lib/remember-the-ruby/rpc.rb",
     "lib/remember-the-ruby/storage.rb",
     "lib/remember-the-ruby/tag.rb",
     "lib/remember-the-ruby/task.rb",
     "lib/remember-the-ruby/task_occurrence.rb",
     "lib/rtr.rb",
     "lib/rtr/api.rb",
     "lib/rtr/command_helper.rb",
     "lib/rtr/commands.rb",
     "remember-the-ruby.gemspec",
     "spec/api_spec.rb",
     "spec/remember-the-ruby_spec.rb",
     "spec/settings.rb",
     "spec/settings.yml.dist",
     "spec/task_spec.rb"
  ]
  s.homepage = %q{http://github.com/ddollar/remember-the-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Ruby interface to Remember the Milk}
  s.test_files = [
    "spec/api_spec.rb",
     "spec/remember-the-ruby_spec.rb",
     "spec/settings.rb",
     "spec/task_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<ddollar-preferences>, [">= 0.1.3"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 1.0.3"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<ddollar-preferences>, [">= 0.1.3"])
      s.add_dependency(%q<term-ansicolor>, [">= 1.0.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<ddollar-preferences>, [">= 0.1.3"])
    s.add_dependency(%q<term-ansicolor>, [">= 1.0.3"])
  end
end
